service: aws-edu-enem-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: us-east-1
  ecr:
    images:
      dashboard_service:
        path: ./services/dashboard_service
        file: Dockerfile
      questions_service:
        path: ./services/questions_service
        file: Dockerfile

functions:
  getQSEmbeddingURL:
    role: arn:aws:iam::710349444454:role/service-role/getQSEmbeddingURLRole
    image:
      name: dashboard_service
      command:
        - getQSEmbeddingURL.lambda_handler
    events:
      - http:
          path: quicksight
          method: get
          integration: lambda
          cors: true
  getEnemQuestions:
    role: arn:aws:iam::710349444454:role/service-role/getEnemQuestionsRole
    image:
      name: questions_service
      command:
        - getEnemQuestions.lambda_handler
    events:
      - http:
          path: questions
          method: get
          integration: lambda
          cors: true
